-- Seed dos 4 perfis de acesso nativos (master/gestor/vendedor/parceiro) pra todos os
-- tenants existentes. Espelha src/data/perfisAcessoSeed.js — o hook usePerfisAcesso.js
-- também faz esse seed no client pra tenants novos criados depois desta migration.
-- Idempotente (ON CONFLICT DO NOTHING).

DO $$
DECLARE
  _tid uuid;
BEGIN
  FOR _tid IN SELECT id FROM public.tenants LOOP

    INSERT INTO public.perfis_acesso (tenant_id, slug, nome, nativo, cor, icon, descricao, permissions)
    VALUES
    (_tid, 'master', 'Master', true, '#1E3A5F', 'ShieldCheck',
      'Acesso total. Gerencia usuários, perfis e integrações.',
      '{"dashboard":{"visualizar":true,"ver_financeiro":true,"exportar":true,"apenas_proprios":false},"pipeline":{"visualizar":true,"criar_editar":true,"excluir":true,"exportar":true,"importar":true,"ver_indicadores":true,"apenas_proprios":false},"metas":{"visualizar":true,"ver_equipe":true,"criar_editar":true,"apenas_proprios":false},"tarefas":{"visualizar":true,"ver_equipe":true,"criar_editar":true,"excluir":true,"apenas_proprios":false},"acoes":{"visualizar":true,"criar_editar":true,"excluir":true,"apenas_proprios":false},"playbooks":{"visualizar":true,"criar_editar":true,"excluir":true},"contatos_canais":{"visualizar":true,"criar_editar":true,"excluir":true,"exportar":true,"apenas_proprios":false},"empresas":{"visualizar":true,"criar_editar":true,"excluir":true,"ver_valores":true,"exportar":true,"apenas_proprios":false},"contatos":{"visualizar":true,"criar_editar":true,"excluir":true,"apenas_proprios":false},"contratos":{"visualizar":true,"criar_editar":true,"excluir":true,"ver_valores":true,"apenas_proprios":false},"pagamentos":{"visualizar":true,"criar_editar":true,"excluir":true,"ver_valores":true,"apenas_proprios":false},"comissoes":{"visualizar":true,"ver_equipe":true,"criar_editar":true,"ver_valores":true,"apenas_proprios":false},"projetos":{"visualizar":true,"criar_editar":true,"excluir":true,"apenas_proprios":false},"customer_success":{"visualizar":true,"criar_editar":true,"apenas_proprios":false},"questionarios":{"visualizar":true,"criar_editar":true,"excluir":true},"documentos":{"visualizar":true,"criar_editar":true,"excluir":true,"exportar":true,"ver_indicadores":true,"apenas_proprios":false},"campanhas":{"visualizar":true,"criar_editar":true,"excluir":true},"parceiros":{"visualizar":true,"criar_editar":true,"excluir":true,"exportar":true},"configuracoes":{"acessar":true,"gerenciar_users":true,"gerenciar_perfis":true,"gerenciar_funis":true,"integracoes":true}}'::jsonb),

    (_tid, 'gestor', 'Gestor', true, '#2E5090', 'Users',
      'Acesso gerencial à equipe. Sem exclusões críticas.',
      '{"dashboard":{"visualizar":true,"ver_financeiro":true,"exportar":true,"apenas_proprios":false},"pipeline":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":true,"importar":true,"ver_indicadores":true,"apenas_proprios":false},"metas":{"visualizar":true,"ver_equipe":true,"criar_editar":true,"apenas_proprios":false},"tarefas":{"visualizar":true,"ver_equipe":true,"criar_editar":true,"excluir":false,"apenas_proprios":false},"acoes":{"visualizar":true,"criar_editar":true,"excluir":false,"apenas_proprios":false},"playbooks":{"visualizar":true,"criar_editar":true,"excluir":false},"contatos_canais":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":true,"apenas_proprios":false},"empresas":{"visualizar":true,"criar_editar":true,"excluir":false,"ver_valores":true,"exportar":true,"apenas_proprios":false},"contatos":{"visualizar":true,"criar_editar":true,"excluir":false,"apenas_proprios":false},"contratos":{"visualizar":true,"criar_editar":true,"excluir":false,"ver_valores":true,"apenas_proprios":false},"pagamentos":{"visualizar":true,"criar_editar":false,"excluir":false,"ver_valores":true,"apenas_proprios":false},"comissoes":{"visualizar":true,"ver_equipe":true,"criar_editar":false,"ver_valores":true,"apenas_proprios":false},"projetos":{"visualizar":true,"criar_editar":true,"excluir":false,"apenas_proprios":false},"customer_success":{"visualizar":true,"criar_editar":true,"apenas_proprios":false},"questionarios":{"visualizar":true,"criar_editar":true,"excluir":false},"documentos":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":true,"ver_indicadores":true,"apenas_proprios":false},"campanhas":{"visualizar":true,"criar_editar":false,"excluir":false},"parceiros":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":true},"configuracoes":{"acessar":true,"gerenciar_users":true,"gerenciar_perfis":false,"gerenciar_funis":true,"integracoes":false}}'::jsonb),

    (_tid, 'vendedor', 'Vendedor', true, '#059669', 'Target',
      'Acesso operacional ao pipeline e tarefas.',
      '{"dashboard":{"visualizar":true,"ver_financeiro":false,"exportar":false,"apenas_proprios":true},"pipeline":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":false,"importar":false,"ver_indicadores":true,"apenas_proprios":true},"metas":{"visualizar":true,"ver_equipe":false,"criar_editar":false,"apenas_proprios":true},"tarefas":{"visualizar":true,"ver_equipe":false,"criar_editar":true,"excluir":false,"apenas_proprios":true},"acoes":{"visualizar":true,"criar_editar":false,"excluir":false,"apenas_proprios":true},"playbooks":{"visualizar":true,"criar_editar":false,"excluir":false},"contatos_canais":{"visualizar":false,"criar_editar":false,"excluir":false,"exportar":false,"apenas_proprios":false},"empresas":{"visualizar":true,"criar_editar":true,"excluir":false,"ver_valores":false,"exportar":false,"apenas_proprios":true},"contatos":{"visualizar":true,"criar_editar":true,"excluir":false,"apenas_proprios":true},"contratos":{"visualizar":true,"criar_editar":false,"excluir":false,"ver_valores":false,"apenas_proprios":true},"pagamentos":{"visualizar":false,"criar_editar":false,"excluir":false,"ver_valores":false,"apenas_proprios":false},"comissoes":{"visualizar":true,"ver_equipe":false,"criar_editar":false,"ver_valores":true,"apenas_proprios":true},"projetos":{"visualizar":true,"criar_editar":false,"excluir":false,"apenas_proprios":true},"customer_success":{"visualizar":true,"criar_editar":false,"apenas_proprios":true},"questionarios":{"visualizar":true,"criar_editar":false,"excluir":false},"documentos":{"visualizar":true,"criar_editar":false,"excluir":false,"exportar":true,"ver_indicadores":true,"apenas_proprios":true},"campanhas":{"visualizar":true,"criar_editar":false,"excluir":false},"parceiros":{"visualizar":false,"criar_editar":false,"excluir":false,"exportar":false},"configuracoes":{"acessar":false,"gerenciar_users":false,"gerenciar_perfis":false,"gerenciar_funis":false,"integracoes":false}}'::jsonb),

    (_tid, 'parceiro', 'Parceiro', true, '#D97706', 'ShieldAlert',
      'Acesso restrito ao próprio pipeline.',
      '{"dashboard":{"visualizar":false,"ver_financeiro":false,"exportar":false,"apenas_proprios":true},"pipeline":{"visualizar":true,"criar_editar":true,"excluir":false,"exportar":false,"importar":false,"ver_indicadores":false,"apenas_proprios":true},"metas":{"visualizar":true,"ver_equipe":false,"criar_editar":false,"apenas_proprios":true},"tarefas":{"visualizar":true,"ver_equipe":false,"criar_editar":true,"excluir":false,"apenas_proprios":true},"acoes":{"visualizar":true,"criar_editar":false,"excluir":false,"apenas_proprios":true},"playbooks":{"visualizar":true,"criar_editar":false,"excluir":false},"contatos_canais":{"visualizar":false,"criar_editar":false,"excluir":false,"exportar":false,"apenas_proprios":false},"empresas":{"visualizar":true,"criar_editar":false,"excluir":false,"ver_valores":false,"exportar":false,"apenas_proprios":true},"contatos":{"visualizar":true,"criar_editar":false,"excluir":false,"apenas_proprios":true},"contratos":{"visualizar":true,"criar_editar":false,"excluir":false,"ver_valores":false,"apenas_proprios":true},"pagamentos":{"visualizar":false,"criar_editar":false,"excluir":false,"ver_valores":false,"apenas_proprios":false},"comissoes":{"visualizar":true,"ver_equipe":false,"criar_editar":false,"ver_valores":true,"apenas_proprios":true},"projetos":{"visualizar":false,"criar_editar":false,"excluir":false,"apenas_proprios":false},"customer_success":{"visualizar":false,"criar_editar":false,"apenas_proprios":false},"questionarios":{"visualizar":true,"criar_editar":false,"excluir":false},"documentos":{"visualizar":true,"criar_editar":false,"excluir":false,"exportar":true,"ver_indicadores":false,"apenas_proprios":true},"campanhas":{"visualizar":true,"criar_editar":false,"excluir":false},"parceiros":{"visualizar":true,"criar_editar":false,"excluir":false,"exportar":false},"configuracoes":{"acessar":false,"gerenciar_users":false,"gerenciar_perfis":false,"gerenciar_funis":false,"integracoes":false}}'::jsonb)

    ON CONFLICT (tenant_id, slug) DO NOTHING;

  END LOOP;
END $$;
